version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sa?schema=public
      - NODE_ENV=production

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sa
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
